name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      # Ignore README.md from find results to avoid unintentionally changes on the release step
      - name: Setup Quickstarter (Project ID)
        run: find . -type f \( ! -name "README.md" \) -exec sed -i 's/PROJECTID/foo/g' {} +
      # Ignore README.md from find results to avoid unintentionally changes on the release step
      - name: Setup Quickstarter (Component ID)
        run: find . -type f \( ! -name "README.md" \) -exec sed -i 's/COMPONENTID/app/g' {} +
      - name: Install Dependencies
        run: npm install
      - name: Release
        env:
          GIT_AUTHOR_NAME: 'Simon Golms'
          GIT_AUTHOR_EMAIL: 'development@gol.ms'
          GIT_COMMITTER_NAME: 'Simon Golms'
          GIT_COMMITTER_EMAIL: 'development@gol.ms'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --extends './.github/.releaserc.js'
