name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    env:
      # Disable husky (git hooks) in CI, see: https://typicode.github.io/husky/#/?id=disable-husky-in-cidocker
      HUSKY: 0
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Ignore README.md from find results to avoid unintentionally changes on the release step
      - name: Setup Quickstarter (Project ID)
        run: find . -type f \( ! -name "README.md" \) -exec sed -i 's/PROJECTID/foo/g' {} +
      # Ignore README.md from find results to avoid unintentionally changes on the release step
      - name: Setup Quickstarter (Component ID)
        run: find . -type f \( ! -name "README.md" \) -exec sed -i 's/COMPONENTID/app/g' {} +
      - name: Install Dependencies
        run: npm ci
      - name: Release
        env:
          GIT_AUTHOR_NAME: 'Simon Golms'
          GIT_AUTHOR_EMAIL: 'development@gol.ms'
          GIT_COMMITTER_NAME: 'Simon Golms'
          GIT_COMMITTER_EMAIL: 'development@gol.ms'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --extends './.github/.releaserc.js'
